### ISSUE TITLE
Type error on `balance[radixToken.id]` in example

### ISSUE THREAD

**Issue by philcockfield** [radixdlt/radixdlt-js#16]
Using version `1.0.4-alpha`, the sample for getting tokens from the facuet.

https://docs.radixdlt.com/alpha/developer/javascript-client-library-guide/quick-start#the-complete-dapp

Has a type error when attempting to use `radixToken.id` as a key to the balance object:

![image](https://user-images.githubusercontent.com/185555/49205863-2f4f0b00-f415-11e8-8b84-c8ddf1aa0064.png)

**Comment by MuncleUscles** [comment]
Yes, it's a mistake, it needs to be `radixToken.id.toString()`

@bucanero Could you update this in the knowledge base?

**Comment by bucanero** [comment]
Document fixed and published:
- https://docs.radixdlt.com/alpha/developer/javascript-client-library-guide/quick-start

Changes:
- replaced "radixToken.id" with "radixToken.id.toString()"

**Comment by bucanero** [comment]
-
