### ISSUE TITLE
Angular/cli issues

### ISSUE THREAD

**Issue by Sinthor2** [radixdlt/radixdlt-js#23]
I tried building an angular/cli-app using radix. i had the following issues:

1.
node_modules/radixdlt/build/module/modules/wallet/RadixKeyPair.d.ts(15,17): error TS2304: Cannot find name 'Long'.

I was able to fix it by adding "import Long from 'Long';" to this file.

2.
node_modules/radixdlt/build/module/modules/universe/RadixNodeConnection.d.ts(5,8): error TS1192: Module '"events"' has no default export.

Fixed it by adding "esModuleInterop": true to the tsconfig.json.

(angular version: 7.2.0, typescript version: 3.2.2)

**Comment by Sajjon** [comment]
Closed since this library is now deprecated.
