### ISSUE TITLE
sending message requires a chat

### ISSUE THREAD

**Issue by jim-obrien-orig** [radixdlt/radixdlt-js#67]
In the java sdk you can send a message with just the from and to address. In the js-sdk a chat is required. This seems inconsistent with the underlying api, is inconsistent with the java sdk,  and also requires a lot of additional overhead.
I wanted to update the js server example to add the ability to send a message and view messages, but the chat interface would make it necessary for me to start a chat, which is not a very expressjs/rest oriented approach.

**Comment by MuncleUscles** [comment]
Could you expand on this?

You can send a message like this https://docs.radixdlt.com/radixdlt-js/examples/code-examples/transaction-management#sending-a-message

You can see messages for an identity you own by looking at the `messagingSystem`:
```
// A list of Radix chat messages in the order they're received
identity.account.messagingSystem.messages 

// Radix chat messages grouped by the other address
identity.account.messagingSystem.chats 

// Subscribe for incoming messages
identity.account.messagingSystem.messageSubject.subscribe(...)
```

**Comment by Sajjon** [comment]
Closed since this library is now deprecated.
