### ISSUE TITLE
Serializer "radix.universe" not implemented

### ISSUE THREAD

**Issue by mttbrt** [radixdlt/radixdlt-js#71]
Using BETANET Universe on Node.js (module version `2.0.0-beta.1`) in Debian Linux I get this error:
```
Serializer "radix.universe" not implemented
```
Given the code:
```
const radixUniverse = require('radixdlt').radixUniverse
const BETANET = require('radixdlt').RadixUniverse.BETANET
radixUniverse.bootstrap(BETANET)
```

**Comment by MuncleUscles** [comment]
Thanks for the report, this is just a warning, it doesn't have any implications for the functionality of the app.

It has been solved in an upcoming release https://github.com/radixdlt/radixdlt-js/pull/73
